const dialogue = {
    // "section": "your dialogue"
    "0": "Kick!",
    "2": "Punch!",
    "4": "Chop!",
    "6": "Block!",
    "8": "Once more now! Kick!",
    "9": "Kick!",
    "10": "Punch!",
    "12": "Chop",
    "14": "And block!",
    "15": "Block!",
    "16": "Don't get cocky,",
    "17": "It's gonna get rocky,",
    "18": "We gonna move down to",
    "19": " the next ya jockey, now!",
    "20": "Duck!",
    "22": "Jump!",
    "24": "Turn!",
    "26": "Pose!",
    "28": "Listen carefully! Jump!",
    "29": "Jump!",
    "30": "Pose!",
    "32": "Duck!",
    "34": "And turn!",
    "35": "Turn!",
    "36": "Hmm, yeah, I see",
    "37": "you're getting better!",
    "38": "Kick to the limit",
    "39": "in order to get her, now",
    "40": "Kick! Punch!",
    "42": "Chop! Block!",
    "44": "Chop! Kick!",
    "46": "Punch! Block!",
    "48": "It's gonna get harder now! Duck and jump!",
    "49": "Duck! Jump!",
    "50": "Turn and pose!",
    "52": "Duck and turn!",
    "54": "Jump and pose!",
    "56": "Come on now! Why don't you follow my words?",
    "57": "Because we're almost done, I'll make it easy at first!",
    "58": "I wanna see if you wanna see what it means",
    "59": "To be the man with the master plan, are you the man now?",
    "60": "Here we go! Now",
    "61": "Kick! Punch! Block!",
    "63": "Chop! Kick! Block!",
    "65": "Block, turn and kick it!",
    "66": "Block! Turn! Kick!",
    "67": "Block! Duck! Punch!",
    "69": "Duck! Duck! Turn!",
    "71": "Jump! Kick! Chop!",
    "72": "And punch! Punch! Punch!",
    "73": "Punch! Punch! Punch!",
    "76": "That's it for today.",
    "78": "Good job, PaRappa. You can go onto the next stage now.",
    "79": "Yahoo! Alright!",
};